version: "3.8"
services:
  expo:
    build: .
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
    volumes:
      - .:/code
      - /code/node_modules
    stdin_open: true
    tty: true
